export function MainPage() {

    return (
        <>
            <div className="maindiv">
                <h1>Kérdőívek</h1>
                <h2>Ezen az oldalon létrehozhatsz kérdőíveket, amiket aztán egy link segítségével másokkal megoszthatsz. A kitöltéseket a profilodban látod minden megadott válasszal.</h2>
                <span>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam quis vehicula mauris. Suspendisse dignissim placerat massa, sit amet laoreet tellus mattis non. Nunc vel commodo nunc. Curabitur in enim eget nunc sagittis lacinia. Curabitur rhoncus tristique imperdiet. Nullam lobortis, nibh nec congue suscipit, dolor lorem elementum nunc, ut elementum purus elit eu est. Aliquam ac aliquet nunc. Etiam facilisis dui non neque bibendum sagittis. Etiam non dictum elit. Sed tristique diam ex, vitae convallis felis suscipit eget.

Morbi pulvinar tellus sem. Sed posuere tempus leo, quis finibus massa pellentesque sit amet. Donec a tempus urna. Phasellus porta eros nec ante euismod semper. Nunc vehicula ex nec libero laoreet euismod. Phasellus ac eros tempor, efficitur erat vel, consectetur dui. Nullam sollicitudin, augue at convallis scelerisque, odio metus rhoncus dui, nec fringilla enim ante vel tortor. Aenean bibendum auctor mauris ac vehicula. Praesent aliquet mollis odio eget ultrices. Nam dapibus orci accumsan scelerisque gravida. Etiam eu tortor sit amet mauris faucibus pulvinar. Sed dapibus placerat libero non vehicula. Nunc id dignissim est, vitae ultricies justo. Quisque mollis sem eget est congue molestie in quis augue. Nulla et sem nec dolor lobortis ornare at a diam.

Pellentesque in nunc non est ornare scelerisque. Aliquam convallis sed nulla id egestas. Praesent eleifend eleifend sollicitudin. Curabitur tempor congue dolor, et suscipit justo tristique viverra. Nam a commodo erat. In varius odio ac eros accumsan finibus. Cras euismod sapien id ipsum elementum rutrum. Donec tempus erat leo, id imperdiet purus molestie a. Aenean sodales consequat nisl gravida mollis. Nulla tincidunt ante vel libero volutpat, hendrerit elementum dolor feugiat. Nunc a tincidunt purus. Praesent id eros dolor. In arcu turpis, fermentum in felis eget, iaculis dapibus magna. Nunc vel turpis in sem sodales pharetra. Sed ullamcorper diam vel nisi fermentum hendrerit.

Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nulla at faucibus lectus. Donec lacus ante, pharetra elementum ex in, tempus porttitor elit. Vivamus a urna eleifend, rutrum leo id, imperdiet arcu. Vestibulum tortor nibh, vulputate quis tellus varius, pharetra scelerisque velit. Etiam aliquet orci id nibh imperdiet porta. Nullam feugiat dui vel odio imperdiet facilisis. Proin sollicitudin neque erat, quis volutpat purus rhoncus ac. In fringilla vestibulum magna, sed aliquet mauris. Aliquam efficitur auctor nulla, sed sollicitudin mi dignissim nec. Ut eros dui, placerat sed accumsan id, rhoncus a neque. Duis interdum tortor mauris, maximus vulputate nisi eleifend non. Vestibulum eu diam eget erat tristique egestas. Donec commodo diam vel ex vestibulum malesuada a eget purus. Vestibulum id pellentesque sapien. Sed justo lectus, tempus ut lorem a, sagittis rhoncus mauris.

Vivamus pulvinar, ligula ut congue interdum, diam massa elementum lacus, ut fermentum sapien nisl nec eros. Vestibulum lacus risus, semper non nunc ultricies, pretium tempor libero. Nunc sit amet augue orci. Sed iaculis ultrices dui et vestibulum. Sed vitae viverra orci. Vivamus nec arcu sit amet est suscipit volutpat nec eu ante. Nunc faucibus euismod elit eu volutpat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum nec elementum ligula. Nulla viverra rhoncus nunc. Fusce eget volutpat nisi.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam quis vehicula mauris. Suspendisse dignissim placerat massa, sit amet laoreet tellus mattis non. Nunc vel commodo nunc. Curabitur in enim eget nunc sagittis lacinia. Curabitur rhoncus tristique imperdiet. Nullam lobortis, nibh nec congue suscipit, dolor lorem elementum nunc, ut elementum purus elit eu est. Aliquam ac aliquet nunc. Etiam facilisis dui non neque bibendum sagittis. Etiam non dictum elit. Sed tristique diam ex, vitae convallis felis suscipit eget.

Morbi pulvinar tellus sem. Sed posuere tempus leo, quis finibus massa pellentesque sit amet. Donec a tempus urna. Phasellus porta eros nec ante euismod semper. Nunc vehicula ex nec libero laoreet euismod. Phasellus ac eros tempor, efficitur erat vel, consectetur dui. Nullam sollicitudin, augue at convallis scelerisque, odio metus rhoncus dui, nec fringilla enim ante vel tortor. Aenean bibendum auctor mauris ac vehicula. Praesent aliquet mollis odio eget ultrices. Nam dapibus orci accumsan scelerisque gravida. Etiam eu tortor sit amet mauris faucibus pulvinar. Sed dapibus placerat libero non vehicula. Nunc id dignissim est, vitae ultricies justo. Quisque mollis sem eget est congue molestie in quis augue. Nulla et sem nec dolor lobortis ornare at a diam.

Pellentesque in nunc non est ornare scelerisque. Aliquam convallis sed nulla id egestas. Praesent eleifend eleifend sollicitudin. Curabitur tempor congue dolor, et suscipit justo tristique viverra. Nam a commodo erat. In varius odio ac eros accumsan finibus. Cras euismod sapien id ipsum elementum rutrum. Donec tempus erat leo, id imperdiet purus molestie a. Aenean sodales consequat nisl gravida mollis. Nulla tincidunt ante vel libero volutpat, hendrerit elementum dolor feugiat. Nunc a tincidunt purus. Praesent id eros dolor. In arcu turpis, fermentum in felis eget, iaculis dapibus magna. Nunc vel turpis in sem sodales pharetra. Sed ullamcorper diam vel nisi fermentum hendrerit.

Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nulla at faucibus lectus. Donec lacus ante, pharetra elementum ex in, tempus porttitor elit. Vivamus a urna eleifend, rutrum leo id, imperdiet arcu. Vestibulum tortor nibh, vulputate quis tellus varius, pharetra scelerisque velit. Etiam aliquet orci id nibh imperdiet porta. Nullam feugiat dui vel odio imperdiet facilisis. Proin sollicitudin neque erat, quis volutpat purus rhoncus ac. In fringilla vestibulum magna, sed aliquet mauris. Aliquam efficitur auctor nulla, sed sollicitudin mi dignissim nec. Ut eros dui, placerat sed accumsan id, rhoncus a neque. Duis interdum tortor mauris, maximus vulputate nisi eleifend non. Vestibulum eu diam eget erat tristique egestas. Donec commodo diam vel ex vestibulum malesuada a eget purus. Vestibulum id pellentesque sapien. Sed justo lectus, tempus ut lorem a, sagittis rhoncus mauris.

Vivamus pulvinar, ligula ut congue interdum, diam massa elementum lacus, ut fermentum sapien nisl nec eros. Vestibulum lacus risus, semper non nunc ultricies, pretium tempor libero. Nunc sit amet augue orci. Sed iaculis ultrices dui et vestibulum. Sed vitae viverra orci. Vivamus nec arcu sit amet est suscipit volutpat nec eu ante. Nunc faucibus euismod elit eu volutpat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum nec elementum ligula. Nulla viverra rhoncus nunc. Fusce eget volutpat nisi.</span>
            </div>
        </>
    );
}